locale: fr

backend:
  name: github
  site_domain: beta.gouv.fr
  repo: betagouv/beta.gouv.fr
  commit_messages:
    create: Création de {{slug}} dans {{collection}} !
    update: Mise à jour de {{slug}} dans {{collection}}
    delete: Suppression de {{slug}} dans {{collection}}
    uploadMedia: Nouvelle image {{path}}
    deleteMedia: Suppression de l'image {{path}}
  squash_merges: true
  open_authoring: true

# Permet d'expérimenter en local
# cf. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# local_backend: true

media_folder: "img/netlifycms"

display_url: https://beta.gouv.fr

# La preview n'est pas utile juste pour modifier des auteurs
show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "."

# Editorial workflow: validate changes through pull requests
publish_mode: editorial_workflow

relation_default_options: &relation_default_options
  widget: relation
  valueField: "{{slug}}"
  displayFields: [title]
  searchFields: [slug, title]

date_field_defaults: &date_field_defaults
  widget: datetime
  format: YYYY-MM-DD
  dateFormat: YYYY-MM-DD
  timeFormat: false
  default: null

collections:
  - name: startups
    label: Produits
    label_singular: Produit
    folder: "content/_startups"
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Objectif
        name: mission
        widget: string
      - label: Nom affiché pour l'administration partenaire
        name: owner
        widget: string
      - label: Détails administrations partenaires 
        name: sponsors
        widget: list
        collapsed: false
        fields:
          - label: Nom
            name: name
            widget: string
          - label: Acronyme
            name: acronym
            widget: string
            required: false
          - label: "Type"
            hint: "Quelle est le type de partenaire ? si vous ne savez pas, vous n'avez pas besoins de compléter"
            name: "type"
            widget: "select"
            required: false
            options:
              - { label: "Administration centrale", value: "administration-centrale" }
              - { label: "Opérateur", value: "operateur" }
              - { label: "Sécurité sociale", value: "securite-sociale" }
              - { label: "Collectivité territoriale ", value: "collectivite-territoriale" }
              - { label: "Autre", value: "autre" }
          - label: "Domaine ministériel"
            hint: "Quelle est le domaine ministériel du partenaire ? si vous ne savez pas, vous n'avez pas besoins de compléter"
            name: "domaine_ministeriel"
            widget: "select"
            required: false
            options:
              - { label: "Affaires étrangères", value: "affaires-etrangeres" }
              - { label: "Affaires sociales", value: "affaires-sociales" }
              - { label: "Agriculture", value: "agriculture" }
              - { label: "Armées", value: "armees" }
              - { label: "Bercy", value: "bercy" }
              - { label: "Culture", value: "culture" }
              - { label: "Education nationnale", value: "education-nat" }
              - { label: "Enseignement supérieur", value: "enseignement-sup" }
              - { label: "Environnement", value: "environnement" }
              - { label: "Intérieur", value: interieur }
              - { label: "Outre-mer", value: "outre-mer" }
              - { label: "Santé", value: "sante" }
              - { label: "Service du Premier Ministre", value: "spm" }
              - { label: "Sport", value: "sport" }
              - { label: "Travail", value: "travail" }
              - { label: "Territoires", value: "territoires" }
              - { label: "Autres", value: "autres" }
      - <<: *relation_default_options
        label: Incubateur
        name: incubator
        collection: incubators
      - label: Lien vers le produit
        name: link
        widget: string
        required: false
      - label: Lien vers le code source
        name: repository
        widget: string
        required: false
      - label: Email de contat
        name: contact
        widget: string
        required: false
      - label: Statistiques d'usage publiques
        name: stats
        widget: boolean
        required: false
      - label: Évènements marquants
        name: events
        label_singular: évènement marquant
        widget: list
        collapsed: false
        fields:
          - label: Type d'évènement
            name: name
            widget: relation
            valueField: "{{slug}}"
            displayFields: ["{{label}} ({{slug}})"]
            searchFields: [slug, label]
            collection: events
          - <<: *date_field_defaults
            label: Date approximative
            name: date
          - label: Commentaire
            name: comment
            widget: string
            required: false
      - label: Phases de la plus ancienne à la plus récente
        name: phases
        label_singular: phase
        widget: list
        hint: Indiquez les étapes de la vie du produit de la plus ancienne à la plus récente.
        collapsed: false
        fields:
          - label: Nom de la phase
            name: name
            widget: relation
            valueField: "{{slug}}"
            displayFields: ["{{label}} ({{slug}})"]
            searchFields: [slug, label]
            collection: phases
          - <<: *date_field_defaults
            label: Date de début
            name: start
          - <<: *date_field_defaults
            label: Date de fin de la phase ou de passage à une autre phase
            name: end
            required: false
          - label: Commentaire
            name: comment
            widget: string
            required: false
      - label: Description
        name: body
        widget: markdown
        default: >
          ## Le contexte
          Chaque fois que l’État élabore un projet de texte législatif ou réglementaire qui porte sur le statut des fonctionnaires, l’État doit le soumettre pour avis aux instances du dialogue social compétentes.

          Ces instances sont :

          - le Conseil supérieur de la fonction publique d’État (CSFPE) ;
          - le Conseil supérieur de la fonction publique territoriale (CSFPT) ;
          - le Conseil supérieur de la fonction publique hospitalière (CSFPH) ;
          - et le Conseil commun de la fonction publique (CCFP), compétent pour examiner les projets de textes dont les dispositions sont transverses aux trois versants de la fonction publique.

          Parmi elles, ce sont les CSFPE et CCFP qui génèrent le plus de travail (le plus de projets de texte et le plus d’amendements). C’est la direction générale de l’administration et de la fonction publique (DGAFP) qui est en charge d’une part, du secrétariat de ces 2 instances et, d’autre part, en charge du traitement des amendements émis par les membres de ces instances à savoir les représentants des organisations syndicales et des employeurs territoriaux.

          Concrètement, la DGAFP doit :

          - établir le calendrier social (dates de réunions des conseils) en fonction de l’actualité des productions normatives ;
          - convoquer les membres de conseils dans le délai et transmettre les projets de texte et rapports de présentation des projets de texte à l’ordre du jour ;
          - recueillir les amendements des partenaires sociaux ;
          - traiter les amendements (rédaction et validation) dans le court délai imparti ;
          - organiser la tenue du débat d’un point de vue à la fois logistique (salle de réunion, chevalets etc.) que sur le fond (regroupements cohérents des amendements, ordonnancement du débat) ;
          - produire un support clair et structuré pour le ministre qui préside les réunions et répond aux amendements en séance ;
          - produire un support clair et structuré pour les partenaires sociaux afin de donner la visibilité à tous les membres sur l’ensemble des amendements déposés et afin de faciliter le suivi du débat en séance et notamment l’ordre de discussion (NB : ce document diffère du précédent car ne contient pas les réponses aux amendements).

          Chaque année, en moyenne on compte : 12 CCFP et 12 CSFPE, avec chacun 5 projets de texte à l’ordre du jour qui génèrent chacun une trentaine d’amendements. De plus, lorsqu’une réforme statutaire est lancée, tous les quatre ans environ, un pic d’activité multiplie par 3 ces volumes pour la DGAFP.


          ## La solution numérique

          Le travail sur les amendements sociaux est relativement similaire à celui sur les amendements parlementaires, si bien que la mécanique de [Zam](https://beta.gouv.fr/startups/zam.html) répond à une partie de la problématique de la DGAFP. 

          Cependant, en l’absence de source structurée de données du côté de l’émetteur des amendements sociaux, Visam devra permettre en plus de saisir les projets de texte ainsi que les amendements eux-mêmes.

          La réussite de Visam pourra être mesurée par :

          - la satisfaction et la fidélité des utilisateurs ;
          - le temps gagné par les agents de la DGAFP et amélioration de la qualité des réponses ;
          - la réduction de leur stress perçu ;
          - l’amélioration de la fluidité des échanges avec les partenaires sociaux tant en amont que pendant la séance d’examen.


          ## Interruption du partenariat

          La solution numérique devait être expérimentée avec la DGAFP sur un CCFP / CSFPE courant 2020. 

          Il avait été envisagé d’associer les partenaires sociaux en tant qu’utilisateurs pour la saisie des amendements. Le produit aurait également être pu proposé aux administrations en charge des CSFPT et CSFPH.
      - label: Description2
        name: body2
        widget: "object"
        fields:
          - label: Titre du contexte
            name: context
            widget: string
          - label: Titre du contexte
            name: contextexp
            widget: text
          - label: Titre du problème
            name: probleme
            widget: string
          - label: Explication du problème
            name: problemeexp
            widget: string
          - label: Titre de la solution
            name: solution
            widget: string
          - label: Explication de la solution
            name: solutionexp
            widget: string
          - label: Titre de la stratégie
            name: strategie
            widget: string
          - label: Explication de la stratégie
            name: strategieexp
            widget: text
  - name: "authors"
    identifier_field: fullname
    label: "Membres"
    label_singular: "Membre"
    description: "Les membres de la communauté beta.gouv.fr. Pour modifier une fiche, clique sur son nom ou recherche-la dans la barre de gauche. Pour ajouter un nouveau membre, direction \"Créer une entrée de type Membre\" !"
    folder: "content/_authors"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Nom complet"
        hint: "Format : Prénom Nom. Ton nom complet est utilisé pour le nom de ta fiche. Attention à ton orthographe !"
        name: "fullname"
        widget: "string"
      - label: "Rôle"
        hint: "Développeuse ? Intrapreneur ? Chargée de développement ? Coach ?"
        name: "role"
        widget: "string"
      - label: "Github"
        hint: "Ton nom d'utilisateur GitHub. Il te permet de rejoindre automatiquement l'organisation GitHub betagouv."
        name: "github"
        widget: "string"
        required: false
      - label: "Avatar"
        hint: "À remplir si tu veux mettre un avatar depuis un site externe. Tu peux aussi laisser vide et mettre une image dans le dossier /img/authors/. À défaut, on regardera si tu as une image sur ton profil Github. En dernier, la fiole beta.gouv.fr sera affichée sur la page communauté. Dans le doute : demande à ton marrain !"
        name: "avatar"
        widget: "string"
        required: false
      - label: "Lien externe"
        hint: "Lien vers une page perso externe."
        name: "link"
        widget: "string"
        required: false
      - label: 'Missions'
        label_singular: "Mission"
        hint: "Ton historique de missions avec nous dans l'ordre chronologique."
        name: 'missions'
        widget: 'list'
        min: 1
        max: 10 # both min and max are required to be apply 
        collapsed: false
        fields:
          - label: "Statut"
            hint: "Quelle est ta relation professionnelle avec nous ?"
            name: "status"
            widget: "select"
            options:
              - { label: "Agent public", value: "admin" }
              - { label: "Indépendant", value: "independent" }
              - { label: "Société ou prestataire de services", value: "service" }
          - label: "Employeur"
            hint: "Si besoin de préciser : ton ministère d'origine, ta SSII, etc."
            name: "employer"
            widget: "string"
            required: false
          - <<: *date_field_defaults
            label: "Date de début"
            hint: "Début de ton contrat ou de ton financement."
            name: "start"
          - <<: *date_field_defaults
            label: "Date de fin"
            hint: "Fin de ton contrat ou de ton financement - tu pourras la modifier plus tard."
            name: "end"
      - label: Startups
        label_singular: Startup
        hint: "Plusieurs choix possibles. Si la startup n'apparait pas encore dans la liste, contacte un administrateur du site !"
        name: startups
        <<: *relation_default_options
        collection: startups
        multiple: true
        required: false
      - label: Anciennes Startups
        label_singular: Ancienne Startup
        hint: "Plusieurs choix possibles : sur quelles startups de la communauté tu as travaillé avant ?"
        name: previously
        <<: *relation_default_options
        collection: startups
        required: false
        multiple: true
      - label: Badges
        name: "badges"
        widget: "select"
        multiple: true
        required: false
        options:
           - { label: "Ségur", value: "segur" }
      - label: Description
        hint: "Raconte-nous qui tu es dans une phrase percutante !"
        name: body
        widget: markdown
        required: false
  - name: incubators
    label: Incubateurs
    label_singular: Incubateur
    folder: "content/_incubators"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Responsable, name: owner, widget: string }
      - { label: Site, name: website, widget: string }
      - { label: Dépôts des produits, name: github, widget: string }
      - { label: Contact, name: contact, widget: string }
      - { label: Adresse, name: address, widget: string }
      - label: Redirections
        label_singular: Redirection
        name: redirect_from
        widget: list
        collapsed: false
        field: { label: Source, name: name, widget: string }
  - name: phases
    label: Phases
    label_singular: Phase
    folder: "content/_phases"
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: status, name: status, widget: string }
      - { label: label, name: label, widget: string }
      - { label: type_label, name: type_label, widget: string }
      - { label: order, name: order, widget: number }
      - { label: short_description, name: short_description, widget: string }
  - name: events
    label: Évènement de SET
    label_singular: Évènement
    folder: "content/_events"
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: label, name: label, widget: string }
