name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        if: "${{ secrets.AUTOMERGE_ACTION_TOKEN || secrets.GITHUB_TOKEN }}"
        env:
          # use default github token is AUTOMERGE_ACTION_TOKEN is not defined (on fork branch), but it won't rerun the tests
          GITHUB_TOKEN: "${ secrets.AUTOMERGE_ACTION_TOKEN || secrets.GITHUB_TOKEN }"
          MERGE_LABELS: "merge it !"
          MERGE_REMOVE_LABELS: "merge it !"
          UPDATE_LABELS: "merge it !"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "30000"
