name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: .github/lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          urls: |
            https://beta.gouv.fr
      - name: debug
        run: |
          echo ${{ steps.lighthouse.outputs.manifest }}
          
