name: Sync 'authors' content with blog.beta.gouv.fr
on:
  #schedule:
  #- cron:  "*/15 * * * *"
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
    - name: Sync
      uses: adrianjost/files-sync-action@v2.1.0
      with:
        FILE_PATTERNS: |
          ^content$
          ^img
        TARGET_REPOS: |
          betagouv/blog.beta.gouv.fr
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
